import Link from "next/link";
import { Navigation } from "../components/navigation";

const benefits = [["⌘", "Parse your resume intelligently", "Extract experience, skills, education, and projects into clear, usable data."], ["◎", "Measure ATS alignment", "Compare your resume against the actual role requirements."], ["✦", "Get actionable improvements", "Receive specific rewrites and preparation ideas grounded in your profile."]];

export default function LandingPage() {
  return <><Navigation newReview={false} /><main className="overflow-hidden pt-20">
    <section className="relative px-6 pb-24 pt-20 md:pb-36 md:pt-28"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_30%_10%,rgba(58,92,204,.18),transparent_50%)] dark:opacity-60" /><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-2"><div className="animate-fade-up space-y-8"><p className="text-xs font-medium tracking-[.2em] text-graytext">AI-POWERED • ATS OPTIMIZED</p><h1 className="max-w-2xl text-5xl font-bold leading-[1.08] tracking-tight md:text-7xl">Turn your resume into your next <span className="bg-gradient-to-br from-[#3A5CCC] to-[#5B7FFF] bg-clip-text text-transparent">opportunity</span></h1><p className="max-w-xl text-lg leading-relaxed text-graytext md:text-xl">Upload your resume, compare it with a job description, and receive ATS insights with AI-powered recommendations.</p><div className="flex flex-wrap gap-3"><Link href="/new-review" className="btn-primary px-6 py-3">Review my resume <span>→</span></Link><a href="#how-it-works" className="rounded-full border bg-white px-6 py-3 text-sm font-semibold transition hover:bg-surface dark:bg-dksurf dark:hover:bg-dkcard">See how it works</a></div></div>
      <div className="relative mx-auto w-full max-w-md animate-float"><div className="card rotate-2 bg-white/90 p-7 backdrop-blur dark:bg-dksurf/90"><div className="mb-8 flex items-center justify-between"><div><p className="text-xs text-graytext">Jordan Davis</p><p className="font-semibold">Senior Product Designer</p></div><span className="chip">Analyzed</span></div><div className="flex items-center gap-7"><div className="grid h-36 w-36 place-items-center rounded-full bg-[conic-gradient(#3A5CCC_0deg_313deg,#E5E5EA_313deg)] p-2"><div className="grid h-full w-full place-items-center rounded-full bg-white dark:bg-dksurf"><strong className="text-4xl">87</strong><span className="text-xs text-graytext">ATS score</span></div></div><div className="space-y-3 text-sm"><p><span className="mr-2 text-blue">●</span>Keywords aligned</p><p><span className="mr-2 text-blue">●</span>Skills matched</p><p><span className="mr-2 text-blue">●</span>Feedback ready</p></div></div></div></div></div></section>
    <section className="border-y bg-white px-6 py-24 dark:bg-dksurf"><div className="mx-auto max-w-7xl"><h2 className="mb-14 text-4xl font-bold tracking-tight md:text-6xl">Why candidates choose <span className="text-blue">ResumeLens</span></h2><div className="grid gap-6 md:grid-cols-3">{benefits.map(([icon, title, description]) => <article key={title} className="card space-y-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue/10 text-xl text-blue">{icon}</span><h3 className="text-xl font-semibold">{title}</h3><p className="leading-relaxed text-graytext">{description}</p></article>)}</div></div></section>
    <section id="how-it-works" className="px-6 py-24"><div className="mx-auto max-w-7xl"><h2 className="mb-14 text-4xl font-bold tracking-tight md:text-6xl">How it <span className="text-blue">works</span></h2><div className="grid gap-10 md:grid-cols-3">{[["01", "Upload Resume", "Drop your PDF or DOCX securely."], ["02", "Add Job Description", "Provide the role you want to pursue."], ["03", "Receive Feedback", "Explore your ATS score and next actions."]].map(([number, title, copy]) => <div key={number} className="space-y-3"><p className="text-sm font-semibold text-blue">{number}</p><h3 className="text-xl font-semibold">{title}</h3><p className="text-graytext">{copy}</p></div>)}</div></div></section>
    <section className="mx-6 mb-10 rounded-[2rem] bg-ink px-7 py-14 text-white dark:bg-dkcard md:mx-auto md:max-w-7xl md:px-14"><p className="max-w-4xl text-3xl font-bold leading-tight md:text-5xl">Your resume is analyzed securely. Choose local Ollama or your preferred AI provider.</p></section>
  </main></>;
}
